"""THE SYNTHETIC SOURCE'S HELD-OUT BLOCK, ITS ONE RESUME ADMISSION, AND THE STREAM A CONTINUING RESUME
REPLAYS (Proposal 05 §8 3.1; register 04-Q5; Proposal 04 SR0; docs/04_CONTRACT.md Q-DATA-9), driven
through DATA's entry points and through the real composition root and loop with real on-disk
checkpoints written under a temporary directory.

    python3 tests/test_holdout.py        # exit 0 = every check passed

WHY IT EXISTS. DATA_SYNTH_HOLDOUT puts the synthetic source under the real sources' held-out law, and
04-Q5 rules it ON. It is built OFF, so the first promise is that OFF is the tree it was built on; the
second is that ON is the real law exactly, per area and keyed by name; the third is the resume rule
that lets a checkpoint written before the lever continue under it -- one admission, counted per area,
and every other move refused by name -- together with the digest that lets a continuing mid-epoch
resume refuse a stream that is not the one its parent was reading. Each check below pins one of them.

  H1  AT 0, THE TREE IT WAS BUILT ON: the synthetic bodies are the generated text whole, nothing is
      held out, no data.holdout.<key> child is minted, and the OFF record's key, offset, size and seam
      are the ones restore_stream_state has always compared; its `why`, and the two UNREACHABLE gates,
      now name DATA_SYNTH_HOLDOUT=0 (checked apart). On a real source the carve equals the law
      recomputed here from the corpus on disk, and the lever changes nothing there.
  H2  AT 1, THE REAL SOURCES' LAW ON SYNTHETIC TEXT: each shipped area holds out 3,000 of its 60,000
      generated bytes, the block is the generated text at the offset rng_for('data.holdout.<key>',
      seed).randint(0, 57000) draws, the body is the rest, and the floor holds; two seeds draw two
      offsets; the gates take the real arm; the val cap binds; and a block that rounds to nothing is
      refused naming DATA_HOLDOUT_FRAC, DATA_VAL_CAP and DATA_SYNTH_HOLDOUT. ADDING AN AREA, AS RULED
      (Q-DATA-9's review): at the shipped DATA_STREAM_BYTES a fifth area shortens every generated
      body to 48,000 bytes and moves every block, and a resume across it is refused naming
      DATA_SEG_MAX, DATA_STREAM_BYTES and DATA_N_PROCESSES with their values, both lengths, the
      DATA_STREAM_BYTES that gives the parent's back, and DATA_SOURCE=real; at that value, appended,
      no block moves and the resume is an add-an-area run; inserted before py, or with the list
      reordered, the blocks keep their offset, size and key and not their text, and it is refused
      naming DATA_AREAS.
  H3  THE ONE ADMISSION: a parent written at 0 (key None, size 0) resumed at 1 is admitted, one per
      area -- a single-area parent reads 1 (SR0's written answer) and a four-area parent 4 -- with the
      names on data.holdout_admitted_names and in a warning that says the parent trained on the
      bytes, Areas.parent_names equal to the record, each DATA_SEG_CONTIG cursor mapped onto the carved
      body as computed here, and the child's data.holdout_overlap its own reading. An add-an-area
      child keeps the new area's overlap (the parent's dict used to overwrite it), and on a real
      source its carried block. The pair is seeded only where the admission can fire -- the synthetic
      source at 1 -- and is ABSENT elsewhere (Q-DATA-9's review). The admission holds only where this
      run generates the parent's text: a child at another length, or with the areas reordered, is
      refused naming what moved; one that appends an area at the parent's length is admitted.
  H4  EVERY OTHER MOVE IS REFUSED: a parent at 1 resumed at 0 is refused naming both settings that
      write a block, DATA_SYNTH_HOLDOUT=1 and DATA_SOURCE=real, and so is a real parent resumed at the
      shipped synthetic source, which DATA_SOURCE=real then restores (Q-DATA-9's review); a doctored
      offset + 1 is refused naming the area and the field; a synthetic parent at 0 resumed on
      DATA_SOURCE=real -- the same key None, size 0 record against a real block -- is a change of
      source, not the admission, and keeps the refusal it had; a real parent resumed on synthetic at
      1 at its own length agrees on offset, size and key and is refused by the block's digest, and
      so is a real corpus changed on disk inside its block at the same length (a byte changed in the
      training body is not); a record without the digest (written before it) is compared on the
      three fields, as it was.
  H5  A CONTINUING MID-EPOCH RESUME: across a 0 -> 1 admission it is refused by name at the `segment`
      stage, before the model exists, with or without a digest in the log; a stream redrawn at
      DATA_SEG_MAX 1700 against a parent at 1800 is refused by the digest; one segment's label alone
      changes the digest; an ordinary continuation continues exactly and reads data.area_added
      PRESENT-and-0 and the admission pair ABSENT, the shipped arm being one it cannot fire on; a
      digest-stripped log warns once, continues exactly and records the child's own digest. The same
      at epoch 1, where stage E's roll wrote the log.
  H6  AT 1, tests/test_continuation.py's 'plain' and 'mint_then_act' shapes continue exactly.
  H7  derive.stream_key IS data/api.py::_holdout_key, on 'code_OOD', 'continual/01_rust' and 'Eng'.
  H8  EVERY DATA STUB'S `LEVERS READ:` NAMES THE LEVERS ITS BODY READS, following the helpers it hands
      `dat` to (Q-DATA-9's review: restore_stream_state said "none" while it read two).

WHAT THIS FILE CANNOT SEE: whether a held-out number read on these blocks means anything. That is
SR0's probe (register §8 3.1-3.2) and its GPU readings; an admitted block is text the parent trained
on, which the warning says and no CPU check can repair. Everything here is an operation check.
"""
import ast
import dataclasses
import os
import random
import re
import shutil
import sys
import tempfile

_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.insert(0, os.path.join(_ROOT, "src"))

import torch                                                       # noqa: E402
torch.set_num_threads(1)

from spine import lever as _lever                                  # noqa: E402
from spine import rng                                              # noqa: E402
from spine import loop                                             # noqa: E402
from spine import derive                                           # noqa: E402
from spine import assemble                                         # noqa: E402
from spine.compose import compose, RefusedRun, _stream_digest      # noqa: E402
from data import api as data_api                                   # noqa: E402

FAILS = []
DATA_DIR = os.path.join(os.path.abspath(_ROOT), "data")
# tests/test_continuation.py's small base: a tenth-size fabric keeps each compose to a few seconds.
BASE = {"DATA_STREAM_BYTES": "60000", "SIG_WARMUP": "20", "FAB_N0": "256", "FAB_SLOTS": "512",
        "DATA_DIR": DATA_DIR}
# The shipped synthetic shape: four areas, each generated at max(DATA_SEG_MAX + 1, 5000,
# DATA_STREAM_BYTES // 4) x 2 = 60,000 bytes, so DATA_HOLDOUT_FRAC 0.05 holds out 3,000 of each.
AREAS = ["eng", "py", "num", "c"]
WHY_OFF = "DATA_SYNTH_HOLDOUT=0 holds nothing out on this source"


def check(name, ok, detail=""):
    print(("PASS " if ok else "FAIL ") + name + (f" -- {detail}" if detail else ""))
    if not ok:
        FAILS.append(name)


def build(**env):
    _lever._reopen_assembly()
    rng.reset_issued()
    e = dict(BASE)
    e.update({k: str(v) for k, v in env.items()})
    return compose(environ=e)


def cfg(**env):
    """DATA's Config under `env` (DATA_DIR pinned), with the issued streams forgotten, for a direct
    call of DATA's entry points."""
    _lever._reopen_assembly()
    rng.reset_issued()
    e = {"DATA_DIR": DATA_DIR}
    e.update({k: str(v) for k, v in env.items()})
    return assemble.build(environ=e)[0]["DATA"]


def areas_of(d, seed=0):
    rng.reset_issued()
    return data_api.open_areas(d, seed=seed)


def generated(d, seed=0):
    """The synthetic text _synthetic_areas generates for `d`, before any block comes out."""
    entries = [e.strip() for e in str(d.areas).split(",") if e.strip()]
    rng.reset_issued()
    raw = data_api._synthetic_areas(d, seed, entries,
                                    [os.path.basename(e.rstrip("/")) for e in entries])[0]
    rng.reset_issued()
    return raw


def drawn_start(label, seed, top):
    """Where rng_for('data.holdout.<key>', seed).randint(0, top) lands, drawn here apart from DATA."""
    return random.Random(rng.derive_seed(f"data.holdout.{derive.stream_key(label)}", seed)).randint(0, top)


def carved(c, offset, size, body_len):
    """A whole-body cursor on the carved body, by the rule Q-DATA-9 states, computed here."""
    at = c if c < offset else (c - size if c >= offset + size else offset)
    return at % body_len


def gate(areas, name):
    return next((g for g in areas.gates if g.name == name), None)


def books(res):
    b = res.report.get("LOOP(flush books)")
    return b if isinstance(b, dict) else {}


def refusal(d, areas, state):
    """restore_stream_state's refusal message, or None where it restored."""
    try:
        data_api.restore_stream_state(d, areas, state)
        return None
    except data_api.CorpusError as e:
        return str(e)


_DATA_TREE = ast.parse(open(data_api.__file__, encoding="utf-8").read())
_DATA_FUNCS = {n.name: n for n in _DATA_TREE.body if isinstance(n, ast.FunctionDef)}


def levers_read(fn):
    """The DATA levers `fn`'s body reads -- every `dat.<name>` that is not a method call -- following
    each module-level helper it hands `dat` to, so a read moved into a helper still counts."""
    seen, out, todo = set(), set(), [fn]
    while todo:
        f = todo.pop()
        if f in seen or f not in _DATA_FUNCS:
            continue
        seen.add(f)
        called = {id(c.func) for c in ast.walk(_DATA_FUNCS[f]) if isinstance(c, ast.Call)}
        for n in ast.walk(_DATA_FUNCS[f]):
            if (isinstance(n, ast.Attribute) and isinstance(n.value, ast.Name) and n.value.id == "dat"
                    and id(n) not in called):
                out.add(n.attr)
            if (isinstance(n, ast.Call) and isinstance(n.func, ast.Name)
                    and any(isinstance(a, ast.Name) and a.id == "dat" for a in n.args)):
                todo.append(n.func.id)
    return out


def levers_declared(fn):
    """The identifiers `fn`'s `LEVERS READ:` block names, split as tests/test_contract.py's K4 reads
    it: on commas outside parentheses, each item's parenthetical dropped; "none" names nothing.
    None where the stub has no such block."""
    doc = ast.get_docstring(_DATA_FUNCS[fn]) or ""
    m = re.search(r"^\s*LEVERS READ:\s*(.+?)(?=^\s*(?:WIRES READ|DID IT FIRE):)", doc, re.M | re.S)
    if m is None:
        return None
    items, buf, depth = [], [], 0
    for ch in m.group(1):
        depth = depth + 1 if ch == "(" else (max(0, depth - 1) if ch == ")" else depth)
        if ch == "," and depth == 0:
            items.append("".join(buf))
            buf = []
        else:
            buf.append(ch)
    items.append("".join(buf))
    names = (re.sub(r"\(.*", "", it, flags=re.S).strip().strip(".") for it in items)
    return {x for x in names if re.fullmatch(r"[a-z_][a-z0-9_]*", x) and x != "none"}


TMP = tempfile.mkdtemp(prefix="holdout_")
try:
    # ---- H7: one normalisation ------------------------------------------------------------------
    _keys = {lab: (derive.stream_key(lab), data_api._holdout_key(lab))
             for lab in ("code_OOD", "continual/01_rust", "Eng")}
    check("H7 derive.stream_key is data/api.py::_holdout_key on 'code_OOD', 'continual/01_rust' and "
          "'Eng' (code_ood, continual_01_rust, eng)",
          all(a == b for a, b in _keys.values())
          and [a for a, _ in _keys.values()] == ["code_ood", "continual_01_rust", "eng"], str(_keys))

    # ---- H8: every DATA stub declares the levers its body reads ---------------------------------
    _stubs = {fn: (levers_declared(fn), levers_read(fn)) for fn in _DATA_FUNCS
              if levers_declared(fn) is not None}
    _off = {fn: (sorted(r - dcl), sorted(dcl - r)) for fn, (dcl, r) in _stubs.items() if dcl != r}
    check("H8 every DATA stub's LEVERS READ names exactly the levers its body reads, through the "
          "helpers it hands `dat` to -- restore_stream_state's among them: source, synth_holdout and "
          "the three that size a synthetic body",
          set(_stubs) >= {"open_areas", "data_plan", "draw_stream", "stream_state",
                          "restore_stream_state"} and not _off
          and _stubs["restore_stream_state"][1] == {"source", "synth_holdout", "n_processes",
                                                    "stream_bytes", "seg_max"},
          f"(read and undeclared, declared and unread) per stub: {_off}")

    # ---- H1: at 0, the tree it was built on -----------------------------------------------------
    d0 = cfg()
    raw0 = generated(d0)
    a0 = areas_of(d0)
    kids0 = sorted(k for k in rng.issued() if k.startswith("data.holdout."))
    check("H1 at 0 the synthetic bodies are the generated text whole, nothing is held out and no "
          "data.holdout.<key> child is minted",
          a0.names == tuple(AREAS) and a0.bodies == raw0 and all(v == b"" for v in a0.holdout.values())
          and all(v == 0 for v in a0.holdout_bytes.values()) and not kids0,
          f"names {a0.names}; bodies equal {a0.bodies == raw0}; children {kids0}")
    check("H1 at 0 the OFF record's key, offset, size and seam are the ones restore_stream_state "
          "compares (None, 0, 0, None)",
          all((r["key"], r["offset"], r["size"], r["seam_at"]) == (None, 0, 0, None)
              for r in a0.rng_holdout.values()), str(a0.rng_holdout["eng"]))
    _g_block, _g_cap = gate(a0, "data.holdout_block"), gate(a0, "data.val_cap_trip")
    check("H1 at 0 the new text: the OFF record's `why` and the overlap sentence name "
          "DATA_SYNTH_HOLDOUT=0, and data.holdout_block and data.val_cap_trip are UNREACHABLE naming it",
          all(r["why"] == WHY_OFF for r in a0.rng_holdout.values())
          and all(v == f"no block to measure -- {WHY_OFF}"
                  for v in a0.counters["data.holdout_overlap"].values())
          and _g_block is not None and not _g_block.reachable
          and "DATA_SYNTH_HOLDOUT=0" in _g_block.reason
          and _g_cap is not None and not _g_cap.reachable and "DATA_SYNTH_HOLDOUT=0" in _g_cap.reason,
          f"{a0.rng_holdout['eng'].get('why')!r}; {_g_block and _g_block.reason[:80]!r}")
    a0z = areas_of(cfg(DATA_HOLDOUT_FRAC=0.0))
    check("H1 at 0 DATA_HOLDOUT_FRAC=0.0 is inert on the synthetic source: no refusal, the same bodies",
          a0z.bodies == raw0)
    # THE REAL SOURCE: the carve recomputed here from the corpus on disk, and the lever inert there. A
    # slash entry is included (Q-DATA-4), whose label is the basename, 01_rust, and whose key is that.
    _renv = {"DATA_SOURCE": "real", "DATA_AREAS": "eng,py,continual/01_rust",
             "DATA_CORPUS_CAP": 200000}
    _dr0 = cfg(**_renv)
    ar0 = areas_of(_dr0)
    ar1 = areas_of(cfg(DATA_SYNTH_HOLDOUT=1, **_renv))
    _bad = []
    for entry in ("eng", "py", "continual/01_rust"):
        lab = os.path.basename(entry)
        rel = entry if "/" in entry else os.path.join("train", entry)
        blob, _present = data_api._read_area(os.path.join(DATA_DIR, rel), 200000)
        n = min(int(len(blob) * float(_dr0.holdout_frac)), int(_dr0.val_cap))
        s = drawn_start(lab, 0, len(blob) - n)
        want = {"key": f"data.holdout.{derive.stream_key(lab)}", "offset": s, "size": n,
                "seam_at": s if 0 < s and s + n < len(blob) else None,
                "overlap": data_api._holdout_overlap(blob[s:s + n], blob[:s] + blob[s + n:])}
        got = {k: ar0.rng_holdout[lab].get(k) for k in want}
        if (got != want or ar0.holdout[lab] != blob[s:s + n]
                or ar0.bodies[lab] != blob[:s] + blob[s + n:]):
            _bad.append((lab, got, want))
    check("H1 on DATA_SOURCE=real the carve is the law recomputed from disk -- block, body, offset, "
          "size, key, seam and overlap -- for three areas, one of them a slash entry", not _bad,
          str(_bad)[:300])
    check("H1 on DATA_SOURCE=real DATA_SYNTH_HOLDOUT changes nothing: every field, counter and gate "
          "of Areas equal at 0 and at 1",
          all(getattr(ar0, f.name) == getattr(ar1, f.name) for f in dataclasses.fields(ar0)),
          str([f.name for f in dataclasses.fields(ar0) if getattr(ar0, f.name) != getattr(ar1, f.name)]))

    # ---- H2: at 1, the real sources' law on synthetic text --------------------------------------
    d1 = cfg(DATA_SYNTH_HOLDOUT=1)
    raw1 = generated(d1)
    a1 = areas_of(d1)
    kids1 = sorted(k for k in rng.issued() if k.startswith("data.holdout."))
    _bad, _starts = [], {}
    for lab in AREAS:
        blob, n = raw1[lab], a1.holdout_bytes[lab]
        s = drawn_start(lab, 0, len(blob) - n)
        _starts[lab] = s
        ok = (len(blob) == 60000 and n == 3000 and len(a1.bodies[lab]) == 57000
              and a1.rng_holdout[lab]["offset"] == s
              and a1.rng_holdout[lab]["key"] == f"data.holdout.{derive.stream_key(lab)}"
              and a1.holdout[lab] == blob[s:s + n] and a1.bodies[lab] == blob[:s] + blob[s + n:]
              and len(a1.bodies[lab]) >= max(int(d1.seg_max) + 1, data_api.MIN_AREA_BYTES)
              and isinstance(a1.counters["data.holdout_overlap"][lab], float))
        if not ok:
            _bad.append(lab)
    check("H2 at 1 each shipped area holds out 3,000 of its 60,000 generated bytes: the block is the "
          "text at the offset rng_for('data.holdout.<key>', seed).randint(0, 57000) draws, the "
          "57,000-byte body is the rest, the floor holds, the overlap is a reading, and the generator "
          "is the one at 0",
          not _bad and raw1 == raw0
          and kids1 == sorted(f"data.holdout.{derive.stream_key(x)}" for x in AREAS),
          f"off: {_bad}; starts {_starts}; children {kids1}")
    _gb, _gc = gate(a1, "data.holdout_block"), gate(a1, "data.val_cap_trip")
    check("H2 at 1 the two gates take the real arm: data.holdout_block fired 4 of 4, data.val_cap_trip "
          "armed and 0 of 4",
          _gb.reachable and _gb.fired and (_gb.value, _gb.threshold) == (4, 4)
          and _gc.reachable and not _gc.fired and (_gc.value, _gc.threshold) == (0, 4),
          f"{_gb}; {_gc}")
    a1s = areas_of(d1, seed=1)
    check("H2 two seeds draw two different offsets in every area",
          all(a1s.rng_holdout[x]["offset"] != a1.rng_holdout[x]["offset"] for x in AREAS),
          str({x: (a1.rng_holdout[x]["offset"], a1s.rng_holdout[x]["offset"]) for x in AREAS}))
    # ADDING AN AREA, AS Q-DATA-9'S REVIEW RULES IT. The generator sizes every area off
    # DATA_STREAM_BYTES // DATA_N_PROCESSES, so a fifth area at the shipped 120,000 shortens all four
    # bodies and moves all four blocks, and the resume across it is refused by name. 150,000 over five
    # is 30,000, as 120,000 over four: at that value, appended, the four bodies are the parent's.
    state1 = data_api.stream_state(d1, areas_of(d1))
    d5u = cfg(DATA_SYNTH_HOLDOUT=1, DATA_N_PROCESSES=5, DATA_AREAS="eng,py,num,c,rust")
    a5u = areas_of(d5u)
    check("H2 a fifth area at the shipped DATA_STREAM_BYTES moves every block: the four are generated "
          "at 48,000 bytes, not 60,000, and hold out 2,400 each",
          all(a5u.bytes_taken[x] == 48000 and a5u.holdout_bytes[x] == 2400 for x in AREAS),
          str({x: (a5u.bytes_taken[x], a5u.holdout_bytes[x]) for x in AREAS}))
    _m = refusal(d5u, a5u, state1) or ""
    check("H2 a resume that adds a fifth area at the shipped DATA_STREAM_BYTES is refused naming "
          "DATA_SEG_MAX, DATA_STREAM_BYTES and DATA_N_PROCESSES with this run's values, the parent's "
          "60,000 bytes beside 48,000, the DATA_STREAM_BYTES that gives them back, and DATA_SOURCE=real",
          all(w in _m for w in ("DATA_SEG_MAX + 1 = 1801", "DATA_STREAM_BYTES=120000 // "
                                "DATA_N_PROCESSES=5) x 2 = 48000 bytes", "recorded 60000",
                                "DATA_STREAM_BYTES=150000 at DATA_N_PROCESSES=5",
                                "resume with DATA_SOURCE=real"))
          and a5u.counters.get("data.state_refused") == 1, _m[:400] or "restored")
    d5 = cfg(DATA_SYNTH_HOLDOUT=1, DATA_N_PROCESSES=5, DATA_AREAS="eng,py,num,c,rust",
             DATA_STREAM_BYTES=150000)
    a5 = areas_of(d5)
    _five_same = (a5.names == tuple(AREAS + ["rust"])
                  and all(a5.rng_holdout[x] == a1.rng_holdout[x] and a5.holdout[x] == a1.holdout[x]
                          and a5.bodies[x] == a1.bodies[x] for x in AREAS))
    _m = refusal(d5, a5, state1)
    check("H2 appended at DATA_STREAM_BYTES 150000, the parent's 60,000 per area, no block moves -- the "
          "four keep their offset, size, key, block and body -- and the resume is an add-an-area run: "
          "data.area_added 1 naming rust, nothing admitted",
          _five_same and _m is None and a5.counters.get("data.area_added") == 1
          and a5.counters.get("data.areas_added_names") == ["rust"]
          and a5.counters.get("data.holdout_admitted") == 0,
          _m or str({x: (a1.rng_holdout[x]["offset"], a5.rng_holdout[x]["offset"]) for x in AREAS}))
    # INSERTED BEFORE py, OR THE LIST REORDERED: the fields hold, the text does not. The generator
    # takes each area's alphabet by position, so py, num and c are other text under the same offset,
    # size and key -- which the field comparison alone admitted.
    d5i = cfg(DATA_SYNTH_HOLDOUT=1, DATA_N_PROCESSES=5, DATA_AREAS="eng,rust,py,num,c",
              DATA_STREAM_BYTES=150000)
    a5i = areas_of(d5i)
    _fields = all((a5i.rng_holdout[x]["offset"], a5i.holdout_bytes[x], a5i.rng_holdout[x]["key"])
                  == (a1.rng_holdout[x]["offset"], a1.holdout_bytes[x], a1.rng_holdout[x]["key"])
                  for x in AREAS)
    _moved = [x for x in AREAS if a5i.holdout[x] != a1.holdout[x]]
    _m = refusal(d5i, a5i, state1) or ""
    check("H2 an area inserted before py keeps every block's offset, size and key and moves py's, num's "
          "and c's text, and the resume is refused naming py's two positions and DATA_AREAS",
          _fields and _moved == ["py", "num", "c"]
          and "area 'py' is at position 2 of this run's areas" in _m and "was at 1" in _m
          and "DATA_AREAS" in _m, f"fields {_fields}; moved {_moved}; {_m[:200] or 'restored'}")
    dro = cfg(DATA_SYNTH_HOLDOUT=1, DATA_AREAS="py,eng,num,c")
    _m = refusal(dro, areas_of(dro), state1) or ""
    check("H2 the same four areas reordered (py,eng,num,c) is refused naming eng's move and DATA_AREAS",
          "area 'eng' is at position 1 of this run's areas" in _m and "DATA_AREAS" in _m,
          _m[:200] or "restored")
    acap = areas_of(cfg(DATA_SYNTH_HOLDOUT=1, DATA_VAL_CAP=1000))
    _gv = gate(acap, "data.val_cap_trip")
    check("H2 at 1 the val cap binds on synthetic text: 1,000 bytes held out per area and "
          "data.val_cap_trip fired 4 of 4",
          all(v == 1000 for v in acap.holdout_bytes.values()) and _gv.fired
          and (_gv.value, _gv.threshold) == (4, 4), f"{acap.holdout_bytes}; {_gv}")
    try:
        areas_of(cfg(DATA_SYNTH_HOLDOUT=1, DATA_HOLDOUT_FRAC=0.0))
        check("H2 at 1 a block that rounds to nothing is refused", False, "open_areas returned")
    except data_api.CorpusError as e:
        check("H2 at 1 DATA_HOLDOUT_FRAC=0.0 is refused, naming DATA_HOLDOUT_FRAC, DATA_VAL_CAP and "
              "DATA_SYNTH_HOLDOUT", all(k in str(e) for k in ("DATA_HOLDOUT_FRAC", "DATA_VAL_CAP",
                                                             "DATA_SYNTH_HOLDOUT")), str(e)[:200])

    # ---- H3 (unit): the admission, per area, with the cursor map --------------------------------
    body_len = len(a1.bodies["eng"])
    _cur = {}
    for lab, where in zip(AREAS, ("below", "inside", "past", "last")):
        o, n = a1.rng_holdout[lab]["offset"], a1.holdout_bytes[lab]
        _cur[lab] = {"below": max(0, o - 1), "inside": o + 5, "past": min(o + n + 7, 59999),
                     "last": o + n - 1}[where]
    p_areas = areas_of(d0)
    p_areas.cursors.update(_cur)
    state0 = data_api.stream_state(d0, p_areas)
    c_areas = areas_of(d1)
    data_api.restore_stream_state(d1, c_areas, state0)
    _want_cur = {lab: carved(_cur[lab], a1.rng_holdout[lab]["offset"], a1.holdout_bytes[lab], body_len)
                 for lab in AREAS}
    cc = c_areas.counters
    check("H3 a four-area parent written at 0, resumed at 1, is admitted once per area: "
          "data.holdout_admitted 4, all four named, Areas.parent_names the record's list",
          cc.get("data.holdout_admitted") == 4 and cc.get("data.holdout_admitted_names") == AREAS
          and c_areas.parent_names == AREAS and cc.get("data.area_added") == 0
          and cc.get("data.state_restored") == 1,
          f"{ {k: cc.get(k) for k in ('data.holdout_admitted', 'data.holdout_admitted_names')} }; "
          f"parent_names {c_areas.parent_names}")
    check("H3 each DATA_SEG_CONTIG cursor is mapped onto the carved body as computed here: below the "
          "block kept, inside it moved to its offset, past it moved down by its size",
          dict(c_areas.cursors) == _want_cur and len({_want_cur[x] - _cur[x] for x in AREAS}) > 1,
          f"parent {_cur}; want {_want_cur}; got {dict(c_areas.cursors)}")
    check("H3 the carved cursor wraps to the head where a tail block held it, and a leading-edge block "
          "sends a cursor inside it to 0",
          data_api._carved_cursor(95, 90, 10, 90) == 0 and data_api._carved_cursor(3, 0, 10, 90) == 0
          and data_api._carved_cursor(12, 0, 10, 90) == 2 and data_api._carved_cursor(89, 90, 10, 90) == 89)
    check("H3 the admitted child's data.holdout_overlap is its own reading, a float per area, not the "
          "parent's 'no block' sentence",
          all(isinstance(cc["data.holdout_overlap"][x], float) for x in AREAS)
          and cc["data.holdout_overlap"] == a1.counters["data.holdout_overlap"],
          str(cc["data.holdout_overlap"]))
    ds0, ds1 = cfg(DATA_AREAS="eng", DATA_N_PROCESSES=1), cfg(DATA_AREAS="eng", DATA_N_PROCESSES=1,
                                                              DATA_SYNTH_HOLDOUT=1)
    s_state = data_api.stream_state(ds0, areas_of(ds0))
    s_child = areas_of(ds1)
    data_api.restore_stream_state(ds1, s_child, s_state)
    check("H3 a single-area parent is admitted with data.holdout_admitted 1 (SR0's written answer)",
          s_child.counters.get("data.holdout_admitted") == 1
          and s_child.counters.get("data.holdout_admitted_names") == ["eng"],
          str({k: v for k, v in s_child.counters.items() if "admitted" in k}))
    # THE ADD-AN-AREA OVERLAP, on the real source, where a block exists on both sides.
    dpa = cfg(DATA_SOURCE="real", DATA_AREAS="eng", DATA_CORPUS_CAP=200000)
    pa = areas_of(dpa)
    dca = cfg(DATA_SOURCE="real", DATA_AREAS="eng,py", DATA_CORPUS_CAP=200000)
    ca = areas_of(dca)
    _own = dict(ca.counters["data.holdout_overlap"])
    data_api.restore_stream_state(dca, ca, data_api.stream_state(dpa, pa))
    check("H3 an add-an-area child on a real source keeps its own overlap reading for every area, the "
          "new one included (the parent's dict used to overwrite it and drop py), and eng's block is "
          "the parent's; the admission pair is ABSENT there",
          ca.counters["data.holdout_overlap"] == _own and set(_own) == {"eng", "py"}
          and ca.counters.get("data.area_added") == 1 and "data.holdout_admitted" not in ca.counters
          and "data.holdout_admitted_names" not in ca.counters
          and ca.holdout["eng"] == pa.holdout["eng"]
          and ca.rng_holdout["eng"]["offset"] == pa.rng_holdout["eng"]["offset"],
          f"own {_own}; after {ca.counters['data.holdout_overlap']}")
    # THE PAIR IS SEEDED ONLY WHERE THE ADMISSION CAN FIRE (Q-DATA-9's review; G4): a same-config
    # resume on each arm. At 0 no synthetic block exists to admit and a real one is never admitted,
    # so the pair is ABSENT there -- UNREACHABLE -- where it read "armed, did not fire".
    _arms = {}
    for tag, env in (("synthetic at 0", {}), ("synthetic at 1", {"DATA_SYNTH_HOLDOUT": 1}),
                     ("real at 0", {"DATA_SOURCE": "real", "DATA_CORPUS_CAP": 200000}),
                     ("real at 1", {"DATA_SOURCE": "real", "DATA_CORPUS_CAP": 200000,
                                    "DATA_SYNTH_HOLDOUT": 1})):
        dd = cfg(**env)
        aa = areas_of(dd)
        _m = refusal(dd, aa, data_api.stream_state(dd, areas_of(dd)))
        _arms[tag] = (_m, {k: aa.counters[k] for k in ("data.holdout_admitted",
                                                       "data.holdout_admitted_names",
                                                       "data.area_added") if k in aa.counters})
    check("H3 the admission pair is PRESENT-and-0 on a resume at DATA_SOURCE=synthetic "
          "DATA_SYNTH_HOLDOUT=1 and ABSENT at 0 and on a real source at either setting; data.area_added "
          "reads 0 on all four",
          _arms == {"synthetic at 0": (None, {"data.area_added": 0}),
                    "synthetic at 1": (None, {"data.holdout_admitted": 0,
                                              "data.holdout_admitted_names": [],
                                              "data.area_added": 0}),
                    "real at 0": (None, {"data.area_added": 0}),
                    "real at 1": (None, {"data.area_added": 0})}, str(_arms))
    # THE ADMISSION HOLDS ONLY WHERE THIS RUN GENERATES THE PARENT'S TEXT (Q-DATA-9's review): the
    # same length, and the same positions. Without the check a child at DATA_STREAM_BYTES 400000
    # carved every block past the parent's 60,000 bytes, and a reordered one carved eng's and py's out
    # of other text, both under a warning that the parent had trained on them.
    d1l = cfg(DATA_SYNTH_HOLDOUT=1, DATA_STREAM_BYTES=400000)
    a1l = areas_of(d1l)
    _m = refusal(d1l, a1l, state0) or ""
    check("H3 an admission at another generated length is refused, naming the parent's 60,000 bytes, "
          "this run's 200,000 with the three levers' values, the DATA_STREAM_BYTES that gives the "
          "parent's back, and DATA_SYNTH_HOLDOUT=0 -- nothing admitted",
          all(w in _m for w in ("held nothing out of area 'eng'", "generated 60000 bytes",
                                "DATA_STREAM_BYTES=400000 // DATA_N_PROCESSES=4) x 2 = 200000 bytes",
                                "DATA_STREAM_BYTES=120000 at DATA_N_PROCESSES=4",
                                "resume at DATA_SYNTH_HOLDOUT=0"))
          and a1l.counters.get("data.holdout_admitted") == 0
          and all(a1l.rng_holdout[x]["offset"] + a1l.holdout_bytes[x] > 60000 for x in AREAS),
          _m[:300] or "admitted")
    d1r = cfg(DATA_SYNTH_HOLDOUT=1, DATA_AREAS="py,eng,num,c")
    _m = refusal(d1r, areas_of(d1r), state0) or ""
    check("H3 an admission with the areas reordered is refused, naming eng's two positions, "
          "DATA_AREAS and DATA_SYNTH_HOLDOUT=0",
          "held nothing out of area 'eng'" in _m and "at position 1 of this run's areas" in _m
          and "DATA_AREAS" in _m and "resume at DATA_SYNTH_HOLDOUT=0" in _m, _m[:300] or "admitted")
    d1a = cfg(DATA_SYNTH_HOLDOUT=1, DATA_N_PROCESSES=5, DATA_AREAS="eng,py,num,c,rust",
              DATA_STREAM_BYTES=150000)
    a1a = areas_of(d1a)
    _m = refusal(d1a, a1a, state0)
    check("H3 an admission that appends a fifth area at the parent's length is admitted: the four "
          "admitted, rust added",
          _m is None and a1a.counters.get("data.holdout_admitted") == 4
          and a1a.counters.get("data.holdout_admitted_names") == AREAS
          and a1a.counters.get("data.areas_added_names") == ["rust"], _m or "")

    # ---- H4 (unit): every other move is refused -------------------------------------------------
    # THE REVERSE NAMES BOTH SETTINGS THAT WRITE A BLOCK (Q-DATA-9's review): the record cannot say
    # which wrote it, and it named DATA_SYNTH_HOLDOUT=1 alone.
    TWO = ("DATA_SOURCE=real, which carves one out of every area, and DATA_SOURCE=synthetic at "
           "DATA_SYNTH_HOLDOUT=1. Resume with the one that wrote it.")
    state1 = data_api.stream_state(d1, areas_of(d1))
    back = areas_of(d0)
    try:
        data_api.restore_stream_state(d0, back, state1)
        check("H4 a parent at 1 resumed at 0 is refused", False, "restored")
    except data_api.CorpusError as e:
        check("H4 a parent at 1 resumed at 0 is refused naming both settings that write a block, "
              "DATA_SOURCE=real and DATA_SYNTH_HOLDOUT=1, with data.state_refused 1",
              "DATA_SYNTH_HOLDOUT=0 holds nothing out" in str(e) and TWO in str(e)
              and back.counters.get("data.state_refused") == 1, str(e)[:300])
    # A REAL PARENT RESUMED AT THE SHIPPED SOURCE: the same refusal, which used to send the operator
    # to DATA_SYNTH_HOLDOUT=1 and a second refusal. DATA_SOURCE=real is the resume that restores.
    rstate = data_api.stream_state(dpa, areas_of(dpa))
    _m0 = refusal(d0, areas_of(d0), rstate) or ""
    _m1 = refusal(d1, areas_of(d1), rstate) or ""
    _mr = refusal(dca, areas_of(dca), rstate)
    check("H4 a real parent resumed at the shipped synthetic source is refused naming DATA_SOURCE=real "
          "beside DATA_SYNTH_HOLDOUT=1; resumed at DATA_SYNTH_HOLDOUT=1 its moved block's refusal names "
          "DATA_SOURCE=real too; DATA_SOURCE=real restores it",
          "'eng' had a 10000-byte held-out block" in _m0 and TWO in _m0
          and "holdout offset=166367 in the checkpoint and 41591 now" in _m1
          and "resume with DATA_SOURCE=real" in _m1 and _mr is None,
          f"{_m0[:160]!r}; {_m1[-160:]!r}; {_mr!r}")
    # THE FIELDS CANNOT SEE A TEXT: a real block and a synthetic one of the same length draw the
    # same offset from one keyed stream over one range. The record's digest can (_block_digest).
    dsl = cfg(DATA_SYNTH_HOLDOUT=1, DATA_STREAM_BYTES=400000)
    asl = areas_of(dsl)
    _same = ((asl.rng_holdout["eng"]["offset"], asl.holdout_bytes["eng"])
             == (rstate["holdout"]["eng"]["offset"], rstate["holdout"]["eng"]["size"]))
    _m = refusal(dsl, asl, rstate) or ""
    _old = dict(rstate, holdout={k: {f: v for f, v in r.items() if f != "digest"}
                                 for k, r in rstate["holdout"].items()})
    _mo = refusal(dsl, areas_of(dsl), _old)
    check("H4 a real parent resumed on synthetic at 1 at its own length (a 200,000-byte body) agrees "
          "on offset, size and key and is refused by the block's digest, naming DATA_SOURCE=real; the "
          "same record without the digest, as written before it, is compared on the three fields and "
          "admitted, as it was",
          _same and "another text in them" in _m and "resume with DATA_SOURCE=real" in _m
          and _mo is None, f"same fields {_same}; {_m[:200]!r}; stripped: {_mo!r}")
    _dig = dict(state1, holdout={k: dict(v) for k, v in state1["holdout"].items()})
    _dig["holdout"]["num"]["digest"] = "0" * 32
    _m = refusal(d1, areas_of(d1), _dig) or ""
    _old1 = dict(state1, holdout={k: {f: v for f, v in r.items() if f != "digest"}
                                  for k, r in state1["holdout"].items()})
    check("H4 a doctored digest is refused naming the area and both digests; a digest-stripped record "
          "of the same run restores",
          "area 'num' has the checkpoint's holdout offset, size and key" in _m and "0" * 32 in _m
          and refusal(d1, areas_of(d1), _old1) is None, _m[:200] or "restored")
    # A REAL CORPUS CHANGED ON DISK UNDER THE SAME LENGTH: one byte inside the held-out block flipped
    # between the parent and the child. No field moves; the digest does. One byte flipped in the
    # training body instead leaves the block, and the resume, alone.
    _cdir = os.path.join(TMP, "corpus")
    os.makedirs(os.path.join(_cdir, "train", "eng"))
    _blob = data_api._read_area(os.path.join(DATA_DIR, "train", "eng"), 200000)[0]
    _file = os.path.join(_cdir, "train", "eng", "text.txt")
    with open(_file, "wb") as fh:
        fh.write(_blob)
    dcx = cfg(DATA_SOURCE="real", DATA_DIR=_cdir, DATA_AREAS="eng", DATA_CORPUS_CAP=200000)
    cx_state = data_api.stream_state(dcx, areas_of(dcx))
    _o, _n = cx_state["holdout"]["eng"]["offset"], cx_state["holdout"]["eng"]["size"]
    _at_body = 50 if _o > 50 else _o + _n + 50          # a training-body byte, outside the block

    def _flip(at):
        with open(_file, "wb") as fh:
            fh.write(_blob[:at] + bytes([_blob[at] ^ 1]) + _blob[at + 1:])

    _flip(_o + 10)
    _m = refusal(dcx, areas_of(dcx), cx_state) or ""
    _flip(_at_body)
    _mb = refusal(dcx, areas_of(dcx), cx_state)
    check("H4 a real corpus changed on disk inside the held-out block, at the same length, is refused "
          "by the digest naming the corpus under DATA_DIR; a byte changed in the training body is not",
          "another text in them" in _m and "the corpus under DATA_DIR changed" in _m and _mb is None,
          f"{_m[:160]!r}; body flip: {_mb!r}")
    doctored = dict(state1, holdout={k: dict(v) for k, v in state1["holdout"].items()})
    doctored["holdout"]["py"]["offset"] += 1
    try:
        data_api.restore_stream_state(d1, areas_of(d1), doctored)
        check("H4 a doctored offset + 1 is refused", False, "restored")
    except data_api.CorpusError as e:
        check("H4 a doctored offset + 1 is refused, naming the area and the field",
              "'py'" in str(e) and "holdout offset=" in str(e), str(e)[:160])
    # A CHANGE OF SOURCE IS NOT THE ADMISSION: a synthetic parent at 0 writes key None, size 0, and a
    # real-source child under the same names holds a block of each -- refused as before the ruling.
    dsw = cfg(DATA_AREAS="eng,py", DATA_N_PROCESSES=2)
    sw_state = data_api.stream_state(dsw, areas_of(dsw))
    dre = cfg(DATA_SOURCE="real", DATA_AREAS="eng,py", DATA_CORPUS_CAP=200000)
    sw_child = areas_of(dre)
    try:
        data_api.restore_stream_state(dre, sw_child, sw_state)
        check("H4 a synthetic parent resumed on DATA_SOURCE=real is refused", False,
              f"restored: {sw_child.counters.get('data.holdout_admitted')}")
    except data_api.CorpusError as e:
        check("H4 a synthetic parent at 0 resumed on DATA_SOURCE=real is refused, not admitted: the "
              "admission is the synthetic source's, and a change of source keeps the refusal it had "
              "(the admission pair ABSENT, a real source being an arm it cannot fire on)",
              "holdout offset=0 in the checkpoint" in str(e)
              and "data.holdout_admitted" not in sw_child.counters, str(e)[:160])

    # ---- H3 / H4 (end to end): through compose, from real checkpoints ----------------------------
    E20 = {"DATA_STREAM_BYTES": "20000"}
    for tag, extra, n_adm in (("four", {"DATA_SEG_CONTIG": "1"}, 4),
                              ("single", {"DATA_AREAS": "eng", "DATA_N_PROCESSES": "1"}, 1)):
        par = build(CKPT_DIR=f"{TMP}/h3{tag}", **E20, **extra)
        rpar = loop.run(par, progress=False)
        kid = build(CKPT_RESUME=f"{TMP}/h3{tag}", CKPT_DIR=f"{TMP}/h3{tag}c", RUN_EPOCHS=2,
                    DATA_RESAMPLE=1, DATA_SYNTH_HOLDOUT=1, **E20, **extra)
        names = list(kid.areas.names)
        warn = [w for w in kid.warnings if w.startswith("DATA_SYNTH_HOLDOUT ADMITTED")]
        rkid = loop.run(kid, max_windows=3, progress=False)
        row = rkid.report.get("DATA(areas.counters)") or {}
        check(f"H3 end to end ({tag}): a finished parent at 0, resumed by a RUN_EPOCHS=2 child at 1, "
              f"is admitted with data.holdout_admitted {n_adm}, one warning naming every area and "
              f"saying the parent trained on the bytes, and the R row printing the pair",
              int(rpar.epochs) == 1 and kid.resume_pos is None and len(warn) == 1
              and all(x in warn[0] for x in names) and "THE PARENT TRAINED ON THOSE BYTES" in warn[0]
              and row.get("data.holdout_admitted") == n_adm
              and row.get("data.holdout_admitted_names") == names
              and kid.areas.parent_names == names
              and all(isinstance(v, float) for v in row.get("data.holdout_overlap", {}).values()),
              f"epochs {rpar.epochs}; warnings {[w[:60] for w in warn]}; row "
              f"{ {k: row.get(k) for k in ('data.holdout_admitted', 'data.holdout_admitted_names')} }")
        if tag == "four":
            # THE CURSORS THE PARENT SAVED, MAPPED: read off its blob and restored into a fresh child's
            # Areas, before any draw moves them (compose's `stream` row advances them at once).
            blob = torch.load(f"{TMP}/h3four/ckpt.pt", map_location="cpu", weights_only=False)
            pd = blob["payload"]["DATA"]
            dk = cfg(DATA_SYNTH_HOLDOUT=1, DATA_SEG_CONTIG=1, **E20)
            ak = areas_of(dk)
            data_api.restore_stream_state(dk, ak, pd)
            _want = {x: carved(int(pd["cursors"][x]), ak.rng_holdout[x]["offset"],
                               ak.holdout_bytes[x], len(ak.bodies[x])) for x in ak.names}
            check("H3 end to end: the cursors a DATA_SEG_CONTIG=1 parent saved are mapped onto the carved "
                  "bodies as computed here", dict(ak.cursors) == _want
                  and any(int(pd["cursors"][x]) != 0 for x in ak.names),
                  f"saved {pd['cursors']}; want {_want}; got {dict(ak.cursors)}")
            check("H3 end to end: the child's report prints DATA's save pair under the _SAVE_COUNTS rule "
                  "-- the parent's one save restored, none in this process before R",
                  (row.get("data.state_written"), row.get("data.state_written_here")) == (1, 0),
                  str((row.get("data.state_written"), row.get("data.state_written_here"))))
    p1 = build(CKPT_DIR=f"{TMP}/h4p", DATA_SYNTH_HOLDOUT=1)
    loop.run(p1, max_windows=10, progress=False)
    try:
        build(CKPT_RESUME=f"{TMP}/h4p", CKPT_DIR=f"{TMP}/h4c")
        check("H4 end to end: a parent at 1 resumed at 0 is refused", False, "composed")
    except data_api.CorpusError as e:
        check("H4 end to end: a parent at 1 resumed at 0 is refused at the restore naming both "
              "settings that write a block", TWO in str(e), str(e)[:160])

    # ---- H5: the continuing mid-epoch resume ----------------------------------------------------
    u = build()
    ru = loop.run(u, max_windows=100, progress=False)
    p = build(CKPT_DIR=f"{TMP}/h5p")
    loop.run(p, max_windows=60, progress=False)
    check("H5 the fresh log's first event carries the stream's digest",
          p.seg_log["events"][0].get("stream") == _stream_digest(p.stream)
          and all("stream" not in ev for ev in p.seg_log["events"][1:]))
    for tag, env, words in (("0 -> 1", {"DATA_SYNTH_HOLDOUT": "1"},
                             ("DATA_SYNTH_HOLDOUT=0", "epoch boundary", "data.holdout_admitted")),
                            ("DATA_SEG_MAX 1800 -> 1700", {"DATA_SEG_MAX": "1700"},
                             ("digest", "DATA_SEG_MAX=1700"))):
        try:
            build(CKPT_RESUME=f"{TMP}/h5p", CKPT_DIR=f"{TMP}/h5x", **env)
            check(f"H5 a continuing {tag} resume is refused", False, "composed")
        except RefusedRun as e:
            check(f"H5 a continuing {tag} resume is refused at the `segment` stage, before the model "
                  f"exists, naming {', '.join(words)}",
                  e.stage == "segment" and e.system.model is None and len(e.refusals) == 1
                  and all(w in e.refusals[0] for w in words), e.refusals[0][:200])
    # ONE SEGMENT'S LABEL ALONE, AND THE OTHER ONE-FIELD MOVES.
    st = u.stream
    lo, hi = st.splice_starts[3], st.splice_starts[4]
    other = next(x for x in AREAS if x != st.labels[lo])
    relabel = dataclasses.replace(st, labels=st.labels[:lo] + [other] * (hi - lo) + st.labels[hi:])
    rebyte = dataclasses.replace(st, bytes=st.bytes[:lo] + bytes([st.bytes[lo] ^ 1]) + st.bytes[lo + 1:])
    moved = dataclasses.replace(st, splice_starts=st.splice_starts[:3] + (lo + 1,) + st.splice_starts[4:])
    check("H5 one segment's label alone changes the digest, as do one byte and one moved splice; the "
          "same stream digests equal",
          _stream_digest(st) == _stream_digest(dataclasses.replace(st))
          and len({_stream_digest(x) for x in (st, relabel, rebyte, moved)}) == 4
          and relabel.bytes == st.bytes)
    c = build(CKPT_RESUME=f"{TMP}/h5p", CKPT_DIR=f"{TMP}/h5c")
    _nodig = [w for w in c.warnings if "carries no stream digest" in w]
    rc = loop.run(c, max_windows=40, progress=False)
    check("H5 an ordinary continuing resume continues exactly, with no digest warning, and reads "
          "data.area_added 0 with the admission pair ABSENT (the shipped arm, DATA_SYNTH_HOLDOUT=0, "
          "is one the admission cannot fire on)",
          rc.loss_curve[:40] == ru.loss_curve[60:100] and not _nodig
          and "data.holdout_admitted" not in c.areas.counters
          and "data.holdout_admitted_names" not in c.areas.counters
          and c.areas.counters.get("data.area_added") == 0,
          f"first differing {next((i for i, (x, y) in enumerate(zip(rc.loss_curve, ru.loss_curve[60:100])) if x != y), None)}")
    blob = torch.load(f"{TMP}/h5p/ckpt.pt", map_location="cpu", weights_only=False)
    del blob["payload"]["LOOP"]["seg_log"]["events"][0]["stream"]
    torch.save(blob, f"{TMP}/h5p/ckpt.pt")
    try:
        build(CKPT_RESUME=f"{TMP}/h5p", CKPT_DIR=f"{TMP}/h5y", DATA_SYNTH_HOLDOUT=1)
        check("H5 a digest-stripped log at 0 -> 1 is refused", False, "composed")
    except RefusedRun as e:
        check("H5 a digest-stripped log is still refused across a 0 -> 1 admission, by name (the "
              "admission is checked first)",
              e.stage == "segment" and "DATA_SYNTH_HOLDOUT=0" in e.refusals[0], e.refusals[0][:160])
    c2 = build(CKPT_RESUME=f"{TMP}/h5p", CKPT_DIR=f"{TMP}/h5d")
    _nodig = [w for w in c2.warnings if "carries no stream digest" in w]
    _stamp = c2.seg_log["events"][0].get("stream") == _stream_digest(c2.stream)
    rc2 = loop.run(c2, max_windows=40, progress=False)
    check("H5 a digest-stripped log warns once, continues exactly, and the child's log records its own "
          "stream's digest", len(_nodig) == 1 and _stamp and rc2.loss_curve[:40] == ru.loss_curve[60:100],
          f"{len(_nodig)} warning(s); stamped {_stamp}")
    # EPOCH 1: the log stage E's roll wrote.
    E1 = {"DATA_STREAM_BYTES": "20000", "RUN_EPOCHS": "2", "DATA_RESAMPLE": "1"}
    u1 = build(**E1)
    ru1 = loop.run(u1, max_windows=134, progress=False)
    p1 = build(CKPT_DIR=f"{TMP}/h5e", **E1)
    loop.run(p1, max_windows=124, progress=False)
    check("H5 at epoch 1 the log stage E wrote at the roll carries that epoch's stream digest",
          int(p1.seg_log["epoch"]) == 1
          and p1.seg_log["events"][0].get("stream") == _stream_digest(p1.stream))
    c1 = build(CKPT_RESUME=f"{TMP}/h5e", CKPT_DIR=f"{TMP}/h5ec", **E1)
    rc1 = loop.run(c1, max_windows=10, progress=False)
    check("H5 at epoch 1 a continuing resume continues exactly",
          c1.resume_pos is not None and rc1.loss_curve[:10] == ru1.loss_curve[124:134],
          f"resume_pos {c1.resume_pos}")
    for tag, env, word in (("DATA_SEG_MAX 1800 -> 1700", {"DATA_SEG_MAX": "1700"}, "digest"),
                           ("0 -> 1", {"DATA_SYNTH_HOLDOUT": "1"}, "DATA_SYNTH_HOLDOUT=0")):
        try:
            build(CKPT_RESUME=f"{TMP}/h5e", CKPT_DIR=f"{TMP}/h5ex", **E1, **env)
            check(f"H5 at epoch 1 a continuing {tag} resume is refused", False, "composed")
        except RefusedRun as e:
            check(f"H5 at epoch 1 a continuing {tag} resume is refused at the `segment` stage",
                  e.stage == "segment" and word in e.refusals[0], e.refusals[0][:160])

    # ---- H6: at 1, the continuation shapes of tests/test_continuation.py -----------------------
    for tag, n1, n2, env in (("plain", 60, 40, {}),
                             ("mint_then_act", 135, 30, {"TOK_GROW_EVERY": 30, "TOK_RETOK_EVERY": 150})):
        env = dict(env, DATA_SYNTH_HOLDOUT=1)
        uu = build(**env)
        ruu = loop.run(uu, max_windows=n1 + n2, progress=False)
        pp = build(CKPT_DIR=f"{TMP}/h6{tag}", **env)
        rpp = loop.run(pp, max_windows=n1, progress=False)
        cc6 = build(CKPT_RESUME=f"{TMP}/h6{tag}", CKPT_DIR=f"{TMP}/h6{tag}c", **env)
        rcc = loop.run(cc6, max_windows=n2, progress=False)
        acts = (books(rpp).get("loop.acts", 0), books(rcc).get("loop.acts", 0))
        check(f"H6 at DATA_SYNTH_HOLDOUT=1 the '{tag}' shape continues exactly"
              + (" (the act inside the child)" if tag == "mint_then_act" else ""),
              cc6.resume_pos is not None and rcc.loss_curve[:n2] == ruu.loss_curve[n1:n1 + n2]
              and cc6.areas.counters.get("data.holdout_admitted") == 0
              and (tag != "mint_then_act" or (acts[0] == 0 and acts[1] >= 1)),
              f"acts parent/child {acts}")
finally:
    shutil.rmtree(TMP, ignore_errors=True)

print(f"\n=== {len(FAILS)} failing ===")
sys.exit(1 if FAILS else 0)
